# Generated by Django 4.2.1 on 2023-07-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_date', models.DateTimeField()),
                ('contact_inquiry', models.CharField(max_length=1000)),
            ],
        ),
    ]
